### ISSUE TITLE
Any theme example please

### ISSUE THREAD

**Issue by ijakparov** [inpsyde/WP-REST-Starter#4]
Hello, could you share any example of wp theme wich using that package?

**Comment by tfrommen** [comment]
Maybe I am misunderstanding this, but this package should not (needed to be) used in a theme.

`WP-REST-Starter` allows to set up custom REST API endpoints or manipulate existing ones by adding fields etc. All of this is **functionality**, and not _presentation_, and should therefoe be part of a plugin.

**Comment by ijakparov** [comment]
Where should I place the code, and hоw to make it load as a part of WordPress?

**Comment by ijakparov** [comment]
Could you provide me a repo of any plugin using this packadge?

**Comment by ijakparov** [comment]
> Maybe I am misunderstanding this, but this package should not (needed to) be used in a theme.
> 
> `WP-REST-Starter` allows to set up custom REST API endpoints or manipulate existing ones by adding fields etc. All of this is **functionality**, and not _presentation_, and should therefore be part of a **plugin**, not theme.

But it also could be used for WordPress Headless in theme, right?
